### ISSUE TITLE
relationship with existing tornado-swagger project?

### ISSUE THREAD

**Issue by miketheman** [mrk-andreev/tornado-swagger#1]
I found [this repo](https://github.com/SerenaFeng/tornado-swagger) a few minutes ago, linked from https://swagger.io/tools/open-source/open-source-integrations/ - noticed this was never up on pypi.

Then I found that you've released this project on pypi - only a little while ago - how well timed!

Have you seen that repo, and how does this project relate to that one?

**Comment by mrk-andreev** [comment]
> Have you seen that repo, and how does this project relate to that one?
This project do the same things but current have different api approach. Tornado-swagger is looking like aiohttp-swagger. 

I plan to active maintain this repo and add new features without breaking changes.
