### ISSUE TITLE
api ocument access

### ISSUE THREAD

**Issue by importTthis** [mrk-andreev/tornado-swagger#11]
How to add access to api document
For example, you need to enter your username and password to see it.

**Comment by importTthis** [comment]
No one?
who can help me?

**Comment by mrk-andreev** [comment]
You can use `tornado-http-auth` + monkey patching like:

https://github.com/mrk-andreev/tornado-swagger/tree/master/examples/under_security

**Comment by importTthis** [comment]
Thank you. I'll take a look

**Comment by importTthis** [comment]
Thank you. I'll take a look
