### ISSUE TITLE
YAML fails to load when IDE uses \t charaters instead of spaces

### ISSUE THREAD

**Issue by jbold569** [mrk-andreev/tornado-swagger#21]
**Describe the bug**
YAML will fail to load with `\t` characters in the docstring. Technically developers should know not to use tabs when writing their yaml docstrings, but the IDE doesn't know the difference better the python lines and yaml lines when their in the same file.

**To Reproduce**
1. replace the spaces in a simple yaml doc string with tabs instead of multiple spaces
2. load the swagger-ui page

**Expected behavior**
Would expect no difference.

**Desktop (please complete the following information):**
 - OS: Win
 - Browser: chrome

**Additional context**
Should be as simple as a replace function to replace `\t` with multiple spaces before `safe_load(...)`

**Comment by mrk-andreev** [comment]
Thanks, it was fixed in version 1.2.3
