### ISSUE TITLE
Can not register StaticFileHandlers

### ISSUE THREAD

**Issue by ylcoder** [mrk-andreev/tornado-swagger#23]
**Describe the bug**
It complains either the args not fit, index out of range when use that directory with path argument for static file handler.  If no args, also complain there is no method defined in the handler.

**To Reproduce**
Add a StaticFileHandler as one of the routes

![image](https://user-images.githubusercontent.com/8109615/78510651-ef183f00-7764-11ea-9290-87aa397a3124.png)

**Expected behavior**
Should be able to ignore the handler if it can not register. A warning message should be enough we can opt in for API documentation

**Screenshots**
N/A

**Desktop (please complete the following information):**
It should not matter

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mrk-andreev** [comment]
Thanks, that was fixed in v1.2.4 (https://github.com/mrk-andreev/tornado-swagger#version-124)

**Comment by ylcoder** [comment]
Thanks a lot Mark.
