### ISSUE TITLE
Can not handler regular expression ? correctly

### ISSUE THREAD

**Issue by ylcoder** [mrk-andreev/tornado-swagger#24]
**Describe the bug**
When we have the API regular expression as /api/myapi/?(\w+).  The final UI screen can not make the test URL to run.  Basically the pattern is making the API without trailing / to work, i.e., the trailing / is optional when there is no path parameters. 

**To Reproduce**
register an API like in the description
go to swagger UI
use try out to test
it always returns 404

**Expected behavior**
IT should interpret ? in regular expression correctly and UI try out should work as expected of the API spec

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by mrk-andreev** [comment]
In example `model_declaration.py` you can find route with regular expression:
https://github.com/mrk-andreev/tornado-swagger/blob/master/examples/model_declaration.py#L134

It is not documented, but we expect that all dynamic arguments will be inside round brackets.
