### ISSUE TITLE
security_definitions not working

### ISSUE THREAD

**Issue by taka97** [mrk-andreev/tornado-swagger#27]
**Describe the bug**
swagger-ui is not working when add security_definitions, UI still work however I cannot click Authorize button.

**To Reproduce**
1. Download [example file](https://github.com/mrk-andreev/tornado-swagger/blob/master/examples/simple_server.py)
2. Replace ```setup_swagger(self._routes)``` to ```setup_swagger(self._routes,
                      security_definitions={
                          "ApiKeyAuth": {
                              'type': 'apiKey',
                              'in': 'header',
                              'name': 'X-API-Key'
                          }
                      })```
3. Run this script, and access [http://localhost:8080/api/doc](http://localhost:8080/api/doc/)

**Expected behavior**
After clicking Authorize button, Authorize dialog is show

**Screenshots**
![image](https://user-images.githubusercontent.com/21365120/82793319-e4437600-9e9a-11ea-8420-ec6fc9e113bb.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138

**Additional context**
I found that [line](https://github.com/mrk-andreev/tornado-swagger/blob/master/tornado_swagger/_builders.py#L140) is incorrect. My solution: ```swagger['securityDefinitions'] = security_definitions```

**Comment by mrk-andreev** [comment]
Fixed in `Version 1.2.11`

Thanks for your report.
