### ISSUE TITLE
Generate documentation from handler methods with no standard names (get, post, etc)

### ISSUE THREAD

**Issue by ioliverm** [mrk-andreev/tornado-swagger#42]
Hi!

We are interested to know how tornado-swagger identifies the handler methods that are scanned for Swagger comments. We'd like to know that because we "tweaked" tornado and our method names are not exactly the standard ones:

```python
class GetStartedApplicationHandler(ApiHandler):
    def _post_impl(self):
        (Swagger comments would go here)
        (code goes here)
```

Thank you very much for your time,

Ivan

**Comment by mrk-andreev** [comment]
I use loop over `handler.SUPPORTED_METHODS`

https://github.com/mrk-andreev/tornado-swagger/blob/master/tornado_swagger/_builders.py#L54
