### ISSUE TITLE
link to swagger.json missing

### ISSUE THREAD

**Issue by flashpixx** [mrk-andreev/tornado-swagger#47]
**Describe the bug**

I try to download the `swagger.json` file for use the definition in a larger system, but the link is missing. In the wiki the link is shown https://github.com/mrk-andreev/tornado-swagger/wiki#example

**To Reproduce**

Building a API with default settings, so call `setup_swagger(myroutes)` with the version 1.2.10 and Tornado 6.1

**Expected behavior**

Link for download in the user-interface

**Screenshots**

On the screenshot there is no link for getting the `swagger.json` file 

<img width="749" alt="Bildschirmfoto 2021-07-12 um 22 10 12" src="https://user-images.githubusercontent.com/1868222/125349658-1b563e80-e35e-11eb-9f5b-b9b8d5bacaf9.png">

**Comment by mrk-andreev** [comment]
Fixed in `Version 1.2.11`

Thanks for your report.
