### ISSUE TITLE
models could not be rendered

### ISSUE THREAD

**Issue by flashpixx** [mrk-andreev/tornado-swagger#48]
**Describe the bug**

I try to define my data models as dataclasses in a external python file and the models will not be used for rendering. If I copy the model into a file which is passed to tornado with a route, it shows "model could not be rendered" on the ui. The logging is setup to info but no output of the console is shown

**To Reproduce**

Creating a file which contains a route and add the $ref to a data model which is stored in another python file. The model for this is not shown in the ui. If you move the model into the file that contains the route, it is shown in the ui, but the details are mossing and an error message is shown (Tornado 6.1 and Tornado_Swagger 1.2.10)

**Expected behavior**

Show data model in the ui also if it is in an external file.

<img width="1466" alt="Bildschirmfoto 2021-07-12 um 22 27 37" src="https://user-images.githubusercontent.com/1868222/125352034-1646be80-e361-11eb-899e-1815fe8e0b1b.png">
<img width="1449" alt="Bildschirmfoto 2021-07-12 um 22 32 13" src="https://user-images.githubusercontent.com/1868222/125352035-1777eb80-e361-11eb-9839-756c7e603ada.png">

**Comment by mrk-andreev** [comment]
1. Please create example for reproduce these issue 
2. Today `tornado-swagger` support only user described models like `examples/model_declaration.py`.
