### ISSUE TITLE
how to ust  file upload in swagger html??

### ISSUE THREAD

**Issue by xiaomujiang** [mrk-andreev/tornado-swagger#55]
post:
  tags:
    - pet
  summary: uploads an image
  operationId: uploadFile
  parameters:
    - name: petId
      in: path
      description: ID of pet to update
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    content:
      multipart/form-data:
        schema:
          properties:
            additionalMetadata:
              type: string
              description: Additional data to pass to server
            file:
              type: string
              description: file to upload
              format: binary
define  like ,  i  use post to upload a file, but generate the web , it not upload file button
can you help me to solve it?

**Comment by mrk-andreev** [comment]
Look like issue in swagger-ui side.
