### ISSUE TITLE
File encoding doesn't work on Windows during pip install for version 1.4.1

### ISSUE THREAD

**Issue by ylcoder** [mrk-andreev/tornado-swagger#56]
The latest version 1.4.1 could not be installed on Windows because encoding mismatch,  This is the error:

Collecting tornado-swagger==1.4.1
  Downloading tornado-swagger-1.4.1.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\myapps\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-install-14k3ux3w\\tornado-swagger_7281cfc875bb4141bac10a2182923f5d\\setup.py'"'
"'; __file__='"'"'C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-install-14k3ux3w\\tornado-swagger_7281cfc875bb4141bac10a2182923f5d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.S
tringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxxx\AppData\Local\Temp\pip-pip-egg-
info-fvhg2cwd'
         cwd: C:\Users\xxxx\AppData\Local\Temp\pip-install-14k3ux3w\tornado-swagger_7281cfc875bb4141bac10a2182923f5d\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxx\AppData\Local\Temp\pip-install-14k3ux3w\tornado-swagger_7281cfc875bb4141bac10a2182923f5d\setup.py", line 32, in <module>
        LONG_DESCRIPTION = f.read()
      File "C:\myapps\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5155: character maps to <undefined>
    ----------------------------------------

Previous versions are fine.

**Comment by luiscoms** [comment]
Same issue here!
There is a Pull Request open #57

**Comment by chelepa** [comment]
Same incident is occurring here awaiting fix

**Comment by mrk-andreev** [comment]
![image](https://user-images.githubusercontent.com/669347/182818930-f436c899-2c18-4992-94ab-db24dc5fea70.png)

Can not reproduce at release 1.4.4 in `pip==22.2.1` & `Windows Server 2022`

**Comment by luiscoms** [comment]
This was fixed in #67
