### ISSUE TITLE
Request to support pyYAML >=5.4.1

### ISSUE THREAD

**Issue by freshbaby77-sudo** [mrk-andreev/tornado-swagger#59]
Hi,

I'm trying to integrate swagger-tornado with our tornado server with kfserving model but not able to pass the dependency conflict from pyYAML 5.4 as our dependencies only rely on pyYAML >= 5.4.1, can you help update pyYAML version in the near future.

Thanks

**Comment by mrk-andreev** [comment]
Thanks.

Fixed in release 1.4.2.

New dependency requirement:
```
PyYAML>=5.4
```
